More templating.

diff --git a/templates/bin/dns_root_agent.j2 b/templates/bin/dns_root_agent.j2
--- a/templates/bin/dns_root_agent.j2
+++ b/templates/bin/dns_root_agent.j2
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-read neuron_external_ip < /etc/neuron.neuronpointer.net
+read external_ip < /etc/{{ groups['dmz'][0] }}.{{ domain }}
 
 ip_regex='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
 
@@ -16,19 +16,22 @@ err_service_reload=4
 err_sed_conf=5
 err_service_restart=6
 
-if ! echo $neuron_external_ip | grep -qE $ip_regex; then
-  fail $err_invalid "Invalid IP address:  ${neuron_external_ip}"
+if ! echo $external_ip | grep -qE $ip_regex; then
+  fail $err_invalid "Invalid IP address:  ${external_ip}"
 fi
 
-if ! grep -qF ' neuron.neuronpointer.net' /etc/hosts; then
-  echo ' neuron.neuronpointer.net' >> /etc/hosts \
+if ! grep -qF ' {{ groups['dmz'][0] }}.{{ domain }}' /etc/hosts; then
+  echo ' {{ groups['dmz'][0] }}.{{ domain }}' >> /etc/hosts \
   || fail $err_append 'Failed to append a line to /etc/hosts.'
 fi
 
-line="${neuron_external_ip}"' neuron\.neuronpointer\.net'
+line="${external_ip}"' {{ groups['dmz'][0] }}.{{ domain }}'
 if ! grep -qF "^${line}$" /etc/hosts; then
+  pattern="$(
+    sed 's/\./\\./g' <<< '{{ groups['dmz'][0] }}.{{ domain }}'
+  )"
   sed -i -E \
-    's/.* neuron\.neuronpointer\.net.*$/'"${line}"'/' \
+    's/.* '"${pattern}"'.*$/'"${line}"'/' \
     /etc/hosts \
   || fail $err_sed_hosts "sed failed:  ${?}"
   /usr/sbin/service dnsmasq force-reload \
