Add missing reference to "create_files.yml" in tasks/main.yml.  Do not attempt to run the cron job, as it is likely to fail, as the dns_internal counterpart may not yet have run at deployment time.  Make the domain name a CNAME for the mail server FQDN, to try to satisfy reverse DNS requirements.  Use neuron.{{ domain }} as the external address and make all other subdomains a CNAME for that, instead of for the raw domain.

diff --git a/files/bin/dns_root_agent b/files/bin/dns_root_agent
--- a/files/bin/dns_root_agent
+++ b/files/bin/dns_root_agent
@@ -1,6 +1,6 @@
 #!/bin/bash
 
-read neuronpointer_ip < /etc/neuronpointer.net
+read neuron_external_ip < /etc/neuron.neuronpointer.net
 
 ip_regex='^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
 
@@ -16,19 +16,19 @@ err_service_reload=4
 err_sed_conf=5
 err_service_restart=6
 
-if ! echo $neuronpointer_ip | grep -qE $ip_regex; then
-  fail $err_invalid "Invalid IP address:  ${neuronpointer_ip}"
+if ! echo $neuron_external_ip | grep -qE $ip_regex; then
+  fail $err_invalid "Invalid IP address:  ${neuron_external_ip}"
 fi
 
-if ! grep -qF ' neuronpointer.net' /etc/hosts; then
-  echo ' neuronpointer.net' >> /etc/hosts \
+if ! grep -qF ' neuron.neuronpointer.net' /etc/hosts; then
+  echo ' neuron.neuronpointer.net' >> /etc/hosts \
   || fail $err_append 'Failed to append a line to /etc/hosts.'
 fi
 
-line="${neuronpointer_ip}"' neuronpointer\.net'
+line="${neuron_external_ip}"' neuron\.neuronpointer\.net'
 if ! grep -qF "^${line}$" /etc/hosts; then
   sed -i -E \
-    's/.* neuronpointer\.net.*$/'"${line}"'/' \
+    's/.* neuron\.neuronpointer\.net.*$/'"${line}"'/' \
     /etc/hosts \
   || fail $err_sed_hosts "sed failed:  ${?}"
   /usr/sbin/service dnsmasq force-reload \
